---
services:
    parcellocker_nginx:
        image: nginx:1.29-alpine-slim
        container_name: parcellocker-nginx
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
    parcellocker_api:
        build: api
        container_name: parcellocker-api
        environment:
            FLAG: someflag
        ports:
            - 8000:8000

    parcellocker_frontend:
        build: frontend
        container_name: parcellocker-frontend
        ports:
            - 3000:3000
